# Generated by Django 5.2.3 on 2025-08-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='landline',
            field=models.CharField(blank=True, null=True, verbose_name='Landline'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
