# Generated by Django 5.2.3 on 2025-08-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_city_userprofile_landline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='Address'),
        ),
    ]
