# Generated by Django 5.2.3 on 2025-10-11 18:00

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_province_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=encrypted_fields.fields.EncryptedTextField(max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='landline',
            field=encrypted_fields.fields.EncryptedIntegerField(blank=True, null=True, verbose_name='Landline'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=encrypted_fields.fields.EncryptedIntegerField(blank=True, null=True, verbose_name='Postal Code'),
        ),
    ]
