# Generated by Django 5.2.3 on 2025-10-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymous',
            field=models.BooleanField(default=False, null=True, verbose_name='َAnonymous Comment'),
        ),
    ]
