# Generated by Django 5.2.3 on 2025-10-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_comment_unique_book_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Title'),
        ),
    ]
