# Generated by Django 5.2.3 on 2025-10-27 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRM', 'Confirmed'), ('PROCESS', 'Processing'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='Pending Payment', max_length=32, verbose_name='Status of order'),
        ),
    ]
