# Generated by Django 5.2.3 on 2025-10-27 19:38

import shop.models
from django.db import migrations, models

from shop.migrate import GenerateUUID


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=shop.models.generate_order_number, editable=False, unique=True),
        ),
        GenerateUUID(
            app_label="shop",
            model_name="Order",
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRM', 'Confirmed'), ('PROCESS', 'Processing'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='Pending Payment', max_length=32, verbose_name='Status of order'),
        ),
    ]
