# Generated by Django 5.2.3 on 2025-10-29 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_order_number_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='books',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='items_count',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.book'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Total number of this item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items_id',
        ),
    ]
