# Generated by Django 5.2.3 on 2025-11-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_invoice_unique_together_invoice_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('order', 'payment')},
        ),
    ]
