# Generated by Django 5.2.3 on 2025-11-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_invoice_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
