# Generated by Django 5.2.3 on 2025-11-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failure'), ('EXPIRE', 'Expired')], default='Pending', verbose_name="Payment's status"),
        ),
    ]
