# Generated by Django 5.2.3 on 2025-11-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_available',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='In Stock'),
        ),
    ]
