# Generated by Django 5.2.3 on 2025-11-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='negative_votes',
            field=models.IntegerField(default=0, verbose_name='Negative Votes'),
        ),
        migrations.AddField(
            model_name='comment',
            name='positive_votes',
            field=models.IntegerField(default=0, verbose_name='Positive Votes'),
        ),
    ]
