# Generated by Django 5.2.3 on 2025-12-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='negative_votes',
            new_name='downvotes',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='positive_votes',
            new_name='upvotes',
        ),
    ]
