# Generated by Django 5.2.3 on 2025-12-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rename_negative_votes_comment_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Approved'), (-1, 'Rejected')], default='Pending', max_length=1),
        ),
    ]
