# Generated by Django 5.2.3 on 2025-12-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (-1, 'Rejected')], default=0),
        ),
    ]
