# Generated by Django 5.2.3 on 2025-07-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrights',
            options={'default_permissions': (), 'managed': False, 'permissions': (('employee_rights', 'Employee rights'),)},
        ),
    ]
