# Generated by Django 5.2.3 on 2025-12-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_permissionrights_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=42, null=True)),
                ('subject', models.CharField(max_length=64)),
                ('body', models.CharField(max_length=2048)),
            ],
        ),
    ]
