# Generated by Django 5.2.3 on 2025-12-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_publicmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicmessage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('CLOSED', 'Closed')], default='Pending Review', max_length=14),
        ),
    ]
